version: "3"
services:
  server:
    image: jetbrains/teamcity-server:2020.2.4
    platform: linux/amd64
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
